packages:
  - 'apps/*'
  - 'modules/*'

catalog:
  # Capacitor
  '@capacitor/android': '^8.0.0'
  '@capacitor/cli': '^8.0.0'
  '@capacitor/core': '^8.0.0'
  # Next.js
  next: '^16.0.0'
  react: '^19.0.0'
  react-dom: '^19.0.0'
  # Styling
  '@tailwindcss/postcss': '^4.0.0'
  tailwindcss: '^4.0.0'
  postcss: '^8.4.0'
  # Linting
  '@eslint/compat': '^2.0.3'
  '@typescript-eslint/eslint-plugin': '^8.57.2'
  '@typescript-eslint/parser': '^8.57.2'
  eslint: '^9.0.0'
  eslint-config-next: '^16.2.1'
  prettier: '^3.8.1'
  # Types
  '@types/node': '^24.0.0'
  '@types/react': '^19.0.0'
  '@types/react-dom': '^19.0.0'
  # Validation
  zod: '^4.3.3'
  # Tooling
  typescript: '^6.0.0'
  turbo: '^2.0.0'
  knip: '^5.88.1'
